# Default values for discord-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default values for botivater-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "botivater"
fullnameOverride: "botivater"

cloudflared:
  token:

discordbot:
  replicaCount: 1
  settings:
    database:
      url:
    discord:
      applicationId:
      botToken:
    config:
      botAdminPanelUrl:
      rabbitmqURI:
    openai:
      apiKey:

api:
  replicaCount: 1
  ingress:
    enabled: false
    className: ""
    annotations: { }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: botivater-api.cluster.local
        paths:
          - path: /
            pathType: Prefix
    tls: [ ]
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  settings:
    database:
      url:
    jwt:
      secret:
    config:
      botAdminPanelUrl:
      rabbitmqURI:
