# Default values for discord-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default values for botivater-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cloudflared:
  token:

rabbitmq:
  auth:
    username:
    password:
  extraConfiguration: |-
    default_vhost = bot
    default_permissions.configure = .*
    default_permissions.read = .*
    default_permissions.write = .*

discordbot:
  settings:
    database:
      url:
    discord:
      applicationId:
      botToken:
    config:
      botAdminPanelUrl:
      rabbitmqURI:
    openai:
      apiKey:

api:
  settings:
    database:
      url:
    jwt:
      secret:
    config:
      botAdminPanelUrl:
      rabbitmqURI:
